image:
  repository: trialax5htd.jfrog.io/docker-local/myservice
  tag: "1.0.0"

replicaCount: 2

service:
  type: ClusterIP
  port: 80

route:
  enabled: true
  host: myservice-dev.apps.internal

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
